language: ruby
rvm:
  - 2.1.2
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/settings.travis.yml config/settings.local.yml
env:
  # Encrypted seekrits. These are done by using the command line 'travis' tool, like so:
  # $ gem install travis
  # $ travis encrypt "secret_api_key: MyFakeSecret"
  # The above command will produce a string like "secure: <encrypted stuff>" which you can paste
  # into this config file.

  # Encrypted api_github
  secure: "GqDfjKz4ZcomhHvz6iePJm5iAuV8aqBwywamkJ70erFqs+NlXs6a4UfjTv/0Cy2OaQz6ns53tUEkX/W8fOmt1twCUpOwbH6PdgN5atwmKUNRrsrHUuJHu1RKaqHVN7VyvS/eKDvkkzK8904I0UQgUyhS3Wo5O7gvdx+p1KIbcQw="
  # Encrypted api_aws_access_key_id
  secure: "LEU5un6GK62ZMM4CT+UNcjnxmJac3STYQlq3p3mJxQWvTZcVejLi5z/wHQ4cCzDqGv+TtNA+1Zdl4uSc7x0xjT5MgK1gkVGGLu7NUDw1gd43z9gBsGYgc/7qQD6ln950m3zCblIUXHTJCdPXJ1piJfQnmQh8b66r4tjmUDxJyMY="
  # Encrypted api_aws_access_key
  secure: "JyBHim1/RnB9GferuxjetICUR/JJ4Fn6sqZKCP1hWLZV4j+M6bM/VJuWkObiz4X7AUFWLBcqlZHeBGvlCosEcLR5nRQtBBvOQt5oY44DWwWqF64kQFK5YSktDosamtWu2faEJVC/h0T8vwrSoSOE/Jp8rZfOpXFKdOcd3gAILk0="
