# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eed99bc8d5f1183e4c22b3cf9a247f0dab8c16c2c0ea7253567cc7cb3fc644765bdbddaef73390f5e9f9d65897351645e57586461a5911cfe0df0d5e5bf03de

test:
  secret_key_base: 43dab899b9b44289bc2361863041fbc5c5f1e3d0a8f97b05c7262f144123d612531b239d02e1aaf080926976d0e9af5b6e6b719d6f7d2df9402c1fbd310f547a

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
