defaults: &defaults
  api_github: <%= ENV["API_GITHUB"] %>
  api_postmark: <%= ENV["API_POSTMARK"] %>
  api_aws_access_key_id: <%= ENV["API_AWS_ACCESS_KEY_ID"] %>
  api_aws_access_key: <%= ENV["API_AWS_ACCESS_KEY"] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  api_github: <%= ENV["API_GITHUB"] %>
  api_postmark: <%= ENV["API_POSTMARK"] %>
  api_aws_access_key_id: <%= ENV["API_AWS_ACCESS_KEY_ID"] %>
  api_aws_access_key: <%= ENV["API_AWS_ACCESS_KEY"] %>

production:
  api_github: <%= ENV["API_GITHUB"] %>
  api_postmark: <%= ENV["API_POSTMARK"] %>
  api_aws_access_key_id: <%= ENV["API_AWS_ACCESS_KEY_ID"] %>
  api_aws_access_key: <%= ENV["API_AWS_ACCESS_KEY"] %>