development:
  api_github: 6729d3df43c6175308b115cc0b77fd3342998e79
  api_postmark: POSTMARK_API_TEST
  api_aws_access_key_id: AKIAIB5GUKUHGACR7VHQ
  api_aws_access_key: ew713I45fDbj02IhDIl9iAHA40PrrTVetbYnDbXN

test:
  api_github: 6729d3df43c6175308b115cc0b77fd3342998e79
  api_postmark: POSTMARK_API_TEST
  api_aws_access_key_id: AKIAIB5GUKUHGACR7VHQ
  api_aws_access_key: ew713I45fDbj02IhDIl9iAHA40PrrTVetbYnDbXN