class AddTagCategoryData < ActiveRecord::Migration
  def change
    biology = TagCategory.find_or_create_by(name: 'Biology')
    ecology = TagCategory.find_or_create_by(name: 'Ecology')
    education = TagCategory.find_or_create_by(name: 'Education')
    psychology = TagCategory.find_or_create_by(name: 'Psychology')
    mathematics = TagCategory.find_or_create_by(name: 'Mathematics')
    chemistry = TagCategory.find_or_create_by(name: 'Chemistry')
    physics = TagCategory.find_or_create_by(name: 'Physics')
    paleontology = TagCategory.find_or_create_by(name: 'Paleontology')
    anthropology = TagCategory.find_or_create_by(name: 'Anthropology')
    engineering = TagCategory.find_or_create_by(name: 'Engineering')
    social_science = TagCategory.find_or_create_by(name: 'Social Science')
    materials_science = TagCategory.find_or_create_by(name: 'Materials Science')
    medicine = TagCategory.find_or_create_by(name: 'Medicine')
    art_and_design = TagCategory.find_or_create_by(name: 'Art and Design')
    data_science = TagCategory.find_or_create_by(name: 'Data Science')
    economics = TagCategory.find_or_create_by(name: 'Economics')
    earth_science = TagCategory.find_or_create_by(name: 'Earth Science')
    neuroscience = TagCategory.find_or_create_by(name: 'Neuroscience')
    political_science = TagCategory.find_or_create_by(name: 'Political Science')
    computer_science = TagCategory.find_or_create_by(name: 'Computer Science')
    organisms = TagCategory.find_or_create_by(name: 'Organisms')
    imaging = TagCategory.find_or_create_by(name: 'Imaging')
    energy = TagCategory.find_or_create_by(name: 'Energy')
    nanotechnology = TagCategory.find_or_create_by(name: 'Nanotechnology')

    analytical_chemistry = Tag.find_or_create_by(name: 'Analytical Chemistry')
    analytical_chemistry.update_attribute(:tag_category, chemistry)
    arthropods = Tag.find_or_create_by(name: 'Arthropods')
    arthropods.update_attribute(:tag_category, organisms)
    bacteria = Tag.find_or_create_by(name: 'Bacteria')
    bacteria.update_attribute(:tag_category, organisms)
    biochemistry = Tag.find_or_create_by(name: 'Biochemistry')
    biochemistry.update_attribute(:tag_category, chemistry)
    cancer_biology = Tag.find_or_create_by(name: 'Cancer Biology')
    cancer_biology.update_attribute(:tag_category, biology)
    cell_biology = Tag.find_or_create_by(name: 'Cell Biology')
    cell_biology.update_attribute(:tag_category, biology)
    cell_culture = Tag.find_or_create_by(name: 'Cell Culture')
    cell_culture.update_attribute(:tag_category, biology)
    chemical_modification = Tag.find_or_create_by(name: 'Chemical Modification')
    chemical_modification.update_attribute(:tag_category, chemistry)
    computational_biology = Tag.find_or_create_by(name: 'Computational Biology')
    computational_biology.update_attribute(:tag_category, biology)
    developmental_biology = Tag.find_or_create_by(name: 'Developmental Biology')
    developmental_biology.update_attribute(:tag_category, biology)
    fish = Tag.find_or_create_by(name: 'Fish')
    fish.update_attribute(:tag_category, organisms)
    genetics_and_genomics = Tag.find_or_create_by(name: 'Genetics and Genomics')
    genetics_and_genomics.update_attribute(:tag_category, biology)
    histology = Tag.find_or_create_by(name: 'Histology')
    histology.update_attribute(:tag_category, biology)
    immunology = Tag.find_or_create_by(name: 'Immunology')
    immunology.update_attribute(:tag_category, medicine)
    imaging_techniques = Tag.find_or_create_by(name: 'Imaging Techniques')
    imaging_techniques.update_attribute(:tag_category, imaging)
    isolation = Tag.find_or_create_by(name: 'Isolation Purification and Separation')
    isolation.update_attribute(:tag_category, biology)
    mammalia = Tag.find_or_create_by(name: 'Mammalia')
    mammalia.update_attribute(:tag_category, organisms)
    materials_science_tag = Tag.find_or_create_by(name: 'Materials Science')
    materials_science_tag.update_attribute(:tag_category, materials_science)
    microbiology = Tag.find_or_create_by(name: 'Microbiology')
    microbiology.update_attribute(:tag_category, biology)
    model_organisms = Tag.find_or_create_by(name: 'Model Organisms')
    model_organisms.update_attribute(:tag_category, organisms)
    molecular_biology = Tag.find_or_create_by(name: 'Molecular Biology')
    molecular_biology.update_attribute(:tag_category, biology)
    nanotechnology_tag = Tag.find_or_create_by(name: 'Nanotechnology')
    nanotechnology_tag.update_attribute(:tag_category, nanotechnology)
    neuroscience = Tag.find_or_create_by(name: 'Neuroscience')
    neuroscience.update_attribute(:tag_category, biology)
    optics_and_phonotics = Tag.find_or_create_by(name: 'Optics and Phonotics')
    optics_and_phonotics.update_attribute(:tag_category, physics)
    organic_photovoltaics = Tag.find_or_create_by(name: 'Organic Photovoltaics')
    organic_photovoltaics.update_attribute(:tag_category, energy)
    other_vertebrates = Tag.find_or_create_by(name: 'Other Vertebrates')
    other_vertebrates.update_attribute(:tag_category, organisms)
    pharmacology = Tag.find_or_create_by(name: 'Pharmacology')
    pharmacology.update_attribute(:tag_category, medicine)
    physics_tag = Tag.find_or_create_by(name: 'Physics')
    physics_tag.update_attribute(:tag_category, physics)
    plants = Tag.find_or_create_by(name: 'Plants')
    plants.update_attribute(:tag_category, organisms)
    proteomics = Tag.find_or_create_by(name: 'Proteomics')
    proteomics.update_attribute(:tag_category, biology)
    solar_energy_conversion = Tag.find_or_create_by(name: 'Solar Energy Conversion')
    solar_energy_conversion.update_attribute(:tag_category, energy)
    spectroscopy = Tag.find_or_create_by(name: 'Spectroscopy')
    spectroscopy.update_attribute(:tag_category, physics)
    stem_cell = Tag.find_or_create_by(name: 'Stem Cell')
    stem_cell.update_attribute(:tag_category, biology)
    structural_biology = Tag.find_or_create_by(name: 'Structural Biology')
    structural_biology.update_attribute(:tag_category, biology)
    synthetic_chemistry = Tag.find_or_create_by(name: 'Synthetic Chemistry')
    synthetic_chemistry.update_attribute(:tag_category, chemistry)
    toxicology = Tag.find_or_create_by(name: 'Toxicology')
    toxicology.update_attribute(:tag_category, medicine)
    viruses = Tag.find_or_create_by(name: 'Viruses')
    viruses.update_attribute(:tag_category, organisms)
    worms = Tag.find_or_create_by(name: 'Worms')
    worms.update_attribute(:tag_category, organisms)
  end
end
